### ISSUE TITLE
[EASY] - Check and fix README.md

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/webpack-modern-boilerplate#11]
For this `#hacktoberfest` event I am looking for someone who help me fixing my readme.md (if needed).

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by yeshijinsel** [comment]
I wanna do this

**Comment by yeshijinsel** [comment]
what the exact error

**Comment by ibbatta** [comment]
@yeshijinsel there are no "exact errors", is just a review of my readme and fix my bad english :)
