### ISSUE TITLE
Check the project and improve my code

### ISSUE THREAD

**Issue by ibbatta** [ibbatta/webpack-modern-boilerplate#6]
For this `#hacktoberfest` event I am looking for someone who help me checking the code and helping me with these tasks:

- [ ] check webpack file and, in case, apply a refactory for "good practices" and performance
- [ ] check tests file and, in case, apply a refactory for "good practices" and performance
- [ ] check project trees and, in case, apply a refactory for "good practices"
- [ ] follow the todo list in the readme

Feel free to open everything you want to grab the t-shirt (I will accept only useful pr)
_(please also support me ---> click on the :star: and I will love you more <3)_

---
FOLLOW THE **HOW TO CONTRIBUTE** PARAGRAPH FOR THE PULL REQUESTS

**Comment by jenniferkaplannyc** [comment]
I'll work on this.

**Comment by ibbatta** [comment]
> I'll work on this.

@jenniferkaplannyc thanks a lot :)

**Comment by jenniferkaplannyc** [comment]
Hi @ibbatta, someone else can work on this if they want.
